.TH LOADNDISDRIVER 8 "1 June 2004"
.SH NAME
loadndisdriver \- load ndis drivers
.SH SYNOPSIS
.B loadndisdriver
.RI [ option ] driver
.SH DESCRIPTION
This manual page documents briefly the
.B loadndisdriver
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in a text file; see below.
.PP
\fBloadndisdriver\fP is a support program for a kernel module. It loads
ndis drivers for the ndiswrapper kernel module.
.SH OPTIONS
A list of options is included below.
.TP
.B \-a
.PP
The programs are documented fully by
.IR /usr/share/doc/ndiswrapper/INSTALL
.SH AUTHOR
This manual page was written by Erik Rigtorp <erik@rigtorp.com>,
for the Debian project (but may be used by others).
