.TH NDISWRAPPER 8 "1 June 2004"
.SH NAME
ndiswrapper, loadndisdriver \- installing ndis drivers
.SH SYNOPSIS
.B ndiswrapper
.RI [ option ]
.SH DESCRIPTION
This manual page documents briefly the
.B ndiswrapper
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in a text file; see below.
.PP
\fBndiswrappper\fP is a support program for a kernel module. It installs
ndis drivers in /etc/ndiswrapper/ so that the ndiswrapper kernel module can
find them and load them with loadndisdriver.
.SH OPTIONS
A list of options is included below.
.TP
.B \-i inffile
Install driver described by inffile.
.TP
.B \-e driver
Remove driver.
.TP
.B \-l 
List installed drivers.
.TP
.B \-m
Write configuration for modprobe.
.PP
The programs are documented fully by
.IR /usr/share/doc/ndiswrapper/INSTALL
.SH AUTHOR
This manual page was written by Erik Rigtorp <erik@rigtorp.com>,
for the Debian project (but may be used by others).
