KERNELDIR = /lib/modules/$(shell uname -r)/build

MODULE=ndiswrapper
OBJS = wrapper.o loader.o winsyms.o ndis.o misc_funcs.o

CFLAGS  = -DLINUX -D__KERNEL__ -DMODULE -DFULLTRACE -I$(KERNELDIR)/include \
  -Wall -Wstrict-prototypes -fomit-frame-pointer    \
  -fno-strict-aliasing -pipe -mpreferred-stack-boundary=2 -O2

$(MODULE).o: $(OBJS)
	$(LD) -r -o $(MODULE).o $(OBJS)

wrapper.o:	wrapper.c loader.h ndis.h loader.h

loader.o:	loader.c

winsyms.o:	winsyms.c

misc_funcs.o:	misc_funcs.c ndis.h
  
all: $(MODULE).o
